export default {
    // 国家代码
    countryCode: {
        AL: "阿尔马尼亚共和国",
        DZ: "阿尔及利亚民主人民共和国",
        AF: "阿富汗伊斯兰国",
        AR: "阿根廷共和国",
        AE: "拉伯联合酋长国",
        AW: "阿鲁巴",
        OM: "阿曼苏丹国",
        AZ: "阿塞拜疆共和国",
        EG: "阿拉伯埃及共和国",
        ET: "埃塞俄比亚",
        IE: "爱尔兰",
        EE: "爱沙尼亚共和国",
        AD: "安道尔公国",
        AO: "安哥拉共和国",
        AI: "安圭拉",
        AG: "安提瓜和巴布达",
        AT: "奥地利共和国",
        AU: "澳大利亚联邦",
        MO: "澳门",
        BB: "巴巴多斯",
        PG: "巴布亚新几内亚独立国",
        BS: "巴哈马联邦",
        PK: "巴基斯坦伊斯兰共和国",
        PY: "巴拉圭共和国",
        PS: "巴勒斯坦国",
        BH: "巴林国",
        PA: "巴拿马共和国",
        BR: "巴西联邦共和国",
        BY: "白俄罗斯共和国",
        BM: "百慕大群岛",
        BG: "保加利亚共和国",
        MP: "北马里亚纳自由联邦",
        BJ: "贝宁共和国",
        BE: "比利时王国",
        IS: "冰岛共和国",
        PR: "波多黎各自由联邦",
        BA: "波斯尼亚和黑塞哥维那",
        PL: "波兰共和国",
        BO: "玻利维亚共和国",
        BZ: "伯利兹",
        BW: "博茨瓦纳共和国",
        BT: "不丹王国",
        BF: "布基纳法索",
        BI: "布隆迪共和国",
        BV: "布维岛",
        KP: "朝鲜民主主义人民共和国",
        GQ: "赤道几内亚共和国",
        DK: "丹麦王国",
        DE: "德意志联邦共和国",
        TL: "东帝汶",
        TG: "多哥共和国",
        DO: "多米尼加共和国",
        DM: "多米尼克联邦",
        RU: "俄罗斯联邦",
        EC: "厄瓜多尔共和国",
        ER: "厄立特里亚国",
        FR: "法兰西共和国",
        FO: "法罗群岛",
        PF: "法属波利尼西亚",
        GF: "法属圭亚那",
        TF: "法属南部领土",
        VA: "梵蒂冈城国",
        PH: "菲律宾共和国",
        FJ: "斐济共和国",
        FI: "芬兰共和国",
        CV: "佛得角共和国",
        FK: "福克兰群岛(马尔维纳斯)",
        GM: "冈比亚共和国",
        CG: "刚果共和国",
        CD: "刚果民主共和国",
        CO: "哥伦比亚共和国",
        CR: "哥斯达黎加共和国",
        GD: "格林纳达",
        GL: "格陵兰",
        GE: "格鲁吉亚共和国",
        CU: "古巴共和国",
        GP: "瓜德罗普",
        GU: "关岛",
        GY: "圭亚那合作共和国",
        KZ: "哈萨克斯坦共和国",
        HT: "海地共和国",
        KR: "大韩民国",
        NL: "荷兰王国",
        AN: "荷属安的列斯",
        HM: "赫德岛和麦克唐纳岛",
        HN: "洪都拉斯共和国",
        KI: "基里巴斯共和国",
        DJ: "吉布提共和国",
        KG: "吉尔吉斯共和国",
        GN: "几内亚共和国",
        GW: "几内亚比绍共和国",
        CA: "加拿大",
        GH: "加纳共和国",
        GA: "加蓬共和国",
        KH: "柬埔寨王国",
        CZ: "捷克共和国",
        ZW: "津巴布韦共和国",
        CM: "喀麦隆共和国",
        QA: "卡塔尔国",
        KY: "开曼群岛",
        CC: "科科斯(基林)群岛",
        KM: "科摩罗伊斯兰联邦共和国",
        CI: "科特迪瓦共和国",
        KW: "科威特国",
        HR: "克罗地亚共和国",
        KE: "肯尼亚共和国",
        CK: "库克群岛",
        LV: "拉脱维亚共和国",
        LS: "莱索托王国",
        LA: "老挝人民民主共和国",
        LB: "黎巴嫩共和国",
        LT: "立陶宛共和国",
        LR: "利比里亚共和国",
        LY: "大阿拉伯利比亚人民社会主义民众国",
        LI: "列支敦士登公国",
        RE: "留尼汪",
        LU: "卢森堡大公国",
        RW: "卢旺达共和国",
        RO: "罗马尼亚",
        MG: "马达加斯加共和国",
        MV: "马尔代夫共和国",
        MT: "马耳他共和国",
        MW: "马拉维共和国",
        MY: "马来西亚",
        ML: "马里共和国",
        MH: "马绍尔群岛共和国",
        MQ: "马提尼克",
        YT: "马约特",
        MU: "毛里求斯共和国",
        MR: "毛里塔尼亚",
        US: "美利坚合众国",
        UM: "美国本土外小岛屿",
        AS: "美属萨摩亚",
        VI: "美属维尔京群岛",
        MN: "蒙古国",
        MS: "蒙特塞拉特",
        BD: "孟加拉人民共和国",
        PE: "秘鲁共和国",
        FM: "密克罗尼西亚联邦",
        MM: "缅甸联邦",
        MD: "摩尔多瓦共和国",
        MA: "摩洛哥王国",
        MC: "摩纳哥公国",
        MZ: "莫桑比克共和国",
        MX: "墨西哥合众国",
        NA: "纳米比亚共和国",
        ZA: "南非共和国",
        GS: "南乔治亚岛和南桑德韦奇岛",
        YU: "南斯拉夫联盟共和国",
        NR: "瑙鲁共和国",
        NP: "尼泊尔王国",
        NI: "尼加拉瓜共和国",
        NE: "尼日尔共和国",
        NG: "尼日利亚联邦共和国",
        NU: "纽埃",
        NO: "挪威王国",
        NF: "诺福克岛",
        PW: "帕劳共和国",
        PN: "皮竺凯恩群岛",
        PT: "葡萄牙共和国",
        MK: "前南斯拉夫马其顿共和国",
        JP: "日本国",
        SE: "瑞典王国",
        CH: "瑞士联邦",
        SV: "萨尔瓦多共和国",
        WS: "萨摩亚独立国",
        SL: "塞拉利昂共和国",
        SN: "塞内加尔共和国",
        CY: "塞浦路斯共和国",
        SC: "塞舌尔共和国",
        SA: "沙特阿拉伯王国",
        CS: "圣诞岛",
        ST: "圣多美和普林西比民主共和国",
        SH: "对赫勒拿",
        KN: "圣革茨和尼维斯联邦",
        LC: "圣卢西亚",
        SM: "圣马力诺共和国",
        PM: "圣皮埃尔和密克隆",
        VC: "圣文森特和格林纳丁斯",
        LK: "斯里兰卡民主社会主义共和国",
        SK: "斯洛伐克共和国",
        SI: "斯洛文尼亚共和国",
        SJ: "斯瓦尔巴群岛",
        SZ: "斯威士兰王国",
        SD: "苏丹共和国",
        SR: "苏里南共和国",
        SB: "年罗门群岛",
        SO: "索马里共和国",
        TJ: "塔吉克斯坦共和国",
        TW: "中国台湾",
        TH: "泰王国",
        TZ: "坦桑尼亚联合共和国",
        TO: "汤加王国",
        TC: "特克斯和凯科斯群岛",
        TT: "特立尼达和多巴哥共和国",
        TN: "突尼斯共和国",
        TV: "图瓦卢",
        TR: "土耳其共和国",
        TM: "土库曼斯坦",
        TK: "托克劳",
        WF: "瓦利斯和富图纳群岛",
        VU: "瓦努阿图共和国",
        GT: "危地马拉共和国",
        VE: "委内瑞拉共和国",
        BN: "文莱达鲁萨兰国",
        UG: "乌干达共和国",
        UA: "乌克兰",
        UY: "乌拉圭东岸共和国",
        UZ: "乌兹别克斯坦共和国",
        ES: "西班牙",
        EH: "西撒哈拉",
        GR: "希腊共和国",
        HK: "香港",
        SG: "新加坡共和国",
        NC: "新喀里多尼亚",
        NZ: "新西兰",
        HU: "匈牙利共和国",
        SY: "阿拉伯叙利亚共和国",
        JM: "牙买加",
        AM: "亚美尼亚共和国",
        YE: "也门共和国",
        IQ: "伊拉克共和国",
        IR: "伊朗伊斯兰共和国",
        IL: "以色列国",
        IT: "意大利共和国",
        IN: "印度共和国",
        ID: "印度尼西亚共和国",
        GB: "大不列颠及北爱尔兰联合王国",
        VG: "英属维尔京群岛",
        IO: "英属印度洋领土",
        JO: "约旦哈希姆王国",
        VN: "越南社会主席共和国",
        ZM: "赞比亚共和国",
        TD: "乍得共和国",
        GI: "直布罗陀",
        CL: "智利共和国",
        CF: "中非共和国",
        CN: "中华人民共和国",
        ME: "黑山",
        RS: "塞尔维亚",
        CW: "库拉索",
        EL: "欧盟",
        JE: "泽西岛",
        GG: "根西岛",
        IM: "马恩岛",
        KV: "科索沃",
        SS: "南苏丹",
        SX: "圣马丁岛",
    },
    // 代码
    codeData: {
        AD: ["SIREN NUMBER", "LEI"],
        AE: ["COMMERCIAL REGISTER NUMBER", "CHAMBER OF COMMERCE NUMBER"],
        AF: ["SIREN NUMBER"],
        AG: ["SIREN NUMBER"],
        AI: ["CIK"],
        AL: ["NIPT"],
        AM: ["SIREN NUMBER", "LEI"],
        AO: ["NIF"],
        AR: ["CUIT"],
        AT: ["EUROPEAN VAT NUMBER", "TRADE REGISTER NUMBER"],
        AU: ["ABN", "ACN"],
        AW: ["COC-NUMBER", "RSIN"],
        AZ: ["COMPANY NUMBER"],
        BA: ["JIB", "UCN"],
        BB: ["COMPANY NUMBER"],
        BD: ["COMPANY NUMBER"],
        BE: ["EUROPEAN VAT NUMBER", "BELGIAN COMPANY NUMBER"],
        BG: ["PIN", "UIC"],
        BH: ["COMMERCIAL REGISTER NUMBER", "CR NUMBER"],
        BI: ["SIREN NUMBER"],
        BJ: ["RCCM NUMBER"],
        BM: ["TRADE REGISTER NUMBER"],
        AD: ["SIREN NUMBER", "LEI"],
        AE: ["COMMERCIAL REGISTER NUMBER", "CHAMBER OF COMMERCE NUMBER"],
        AF: ["SIREN NUMBER"],
        AG: ["SIREN NUMBER"],
        AI: ["CIK"],
        AL: ["NIPT"],
        AM: ["SIREN NUMBER", "LEI"],
        AO: ["NIF"],
        AR: ["CUIT"],
        AT: ["EUROPEAN VAT NUMBER", "TRADE REGISTER NUMBER"],
        AU: ["ABN", "ACN"],
        AW: ["COC-NUMBER", "RSIN"],
        AZ: ["COMPANY NUMBER"],
        BA: ["JIB", "UCN"],
        BB: ["COMPANY NUMBER"],
        BD: ["COMPANY NUMBER"],
        BE: ["EUROPEAN VAT NUMBER", "BELGIAN COMPANY NUMBER"],

        BG: ["PIN", "UIC"],
        BI: ["SIREN NUMBER"],
        BJ: ["RCCM NUMBER"],
        BM: ["TRADE REGISTER NUMBER"],
        BN: ["SIREN NUMBER"],
        BO: ["MATRICULA DE COMERCIO", "NIT"],
        BR: ["CNPJ", "NIRE"],
        BS: ["TRADE REGISTER NUMBER"],
        BT: ["TICKER SYMBOL"],
        BF: ["SIREN NUMBER"],
        BW: ["ENTERPRISE NUMBER"],
        BY: ["INN", "OKPO"],
        BZ: ["LEI", "CIK"],
        CA: ["CORPORATION NUMBER", "EIN"],
        CD: ["SIREN NUMBER"],
        CF: ["SIREN NUMBER"],
        CG: ["SIREN NUMBER"],
        CH: ["CH-NUMBER", "UID"],
        CI: ["SIREN NUMBER"],
        CL: ["RUT"],
        CM: ["NIU"],
        CN: ["USCI", "OC"],
        CO: ["NIT"],
        CR: ["TRADE REGISTER NUMBER"],
        CU: ["SIREN NUMBER"],
        CV: ["SIREN NUMBER"],
        CW: ["CIK ", "COC-NUMBER"],
        CY: ["VAT NUMBER", "TRADE REGISTER NUMBER"],
        CZ: ["VAT NUMBER", "TRADE REGISTER NUMBER"],
        DE: ["EUROPEAN VAT NUMBER", "UST-IDNR."],
        DJ: ["TRADE REGISTER NUMBER"],
        DK: ["CVR-NUMBER", "P-NUMBER", "TRADE REGISTER NUMBER"],
        DM: ["LEI", "SIREN NUMBER"],
        DO: ["TRADE REGISTER NUMBER"],
        DZ: ["NRC NUMBER"],
        EC: ["RUC"],
        EE: ["VAT NUMBER", "TRADE REGISTER NUMBER"],
        EG: ["COMMERCIAL REGISTER NUMBER", "INDUSTRIAL LICENSE"],
        EL: ["EUROPEAN VAT NUMBER"],
        ER: ["SIREN NUMBER"],
        ES: ["EUROPEAN VAT NUMBER", "NIF"],
        ET: ["SIREN NUMBER"],
        FI: ["BUSINESS ID", "EUROPEAN VAT NUMBER"],
        FJ: ["LEI"],
        FM: ["IMO NUMBER"],
        FR: ["EUROPEAN VAT NUMBER", "SIREN NUMBER"],
        GA: ["SIREN NUMBER"],
        JE: ["TRADE REGISTER NUMBER"],
        GB: ["COMPANY NUMBER", "VAT NUMBER"],
        GD: ["SIREN NUMBER", "LEI"],
        GE: ["SWIFT CODE"],
        GG: ["TRADE REGISTER NUMBER"],
        GH: ["RGD NUMBER"],
        GI: ["LEI", "COMPANY NUMBER"],
        GM: ["SIREN NUMBER"],
        GN: ["SIREN NUMBER"],
        GQ: ["SIREN NUMBER"],
        GR: ["AFM", "EUROPEAN VAT NUMBER"],
        GT: ["NIT"],
        GW: ["SIREN NUMBER"],
        GY: ["LEI"],
        HK: ["TRADE REGISTER NUMBER"],
        HN: ["LEI"],
        HR: ["OIB", "MBS"],
        HT: ["SIREN NUMBER"],
        HU: ["TRADE REGISTER NUMBER", "STATISTICAL NUMBER"],
        ID: ["TIN", "CIK"],
        IE: ["TRADE REGISTER NUMBER"],
        IL: ["TRADE REGISTER NUMBER", "CIK"],
        IM: ["TRADE REGISTER NUMBER"],
        IN: ["CIN", "TRADE REGISTER NUMBER"],
        IQ: ["COMMERCIAL REGISTER NUMBER", "CHAMBER OF COMMERCE NUMBER"],
        IR: ["COMMERCIAL REGISTER NUMBER", "CHAMBER OF COMMERCE NUMBER"],
        IS: ["VAT NUMBER", "KENNITALA"],
        IT: ["CCIAA", "EUROPEAN VAT NUMBER"],
        JM: ["BUSINESS REGISTRATION NUMBER", "COMPANY NUMBER"],
        JO: ["COMMERCIAL REGISTER NUMBER", "CHAMBER OF COMMERCE NUMBER"],
        JP: ["CIK", "LEI"],
        KE: ["TRADE REGISTER NUMBER"],
        KG: ["LEI"],
        KH: ["SIREN NUMBER"],
        KI: ["LEI"],
        KM: ["SIREN NUMBER"],
        KN: ["LEI"],
        KP: ["SIREN NUMBER"],
        KR: ["VAT NUMBER", "CORPORATE REGISTERED NUMBER"],
        KV: ["TRADE REGISTER NUMBER"],
        KW: ["COMMERCIAL REGISTER NUMBER", "CHAMBER OF COMMERCE NUMBER"],
        KY: ["CIK", "TRADE REGISTER NUMBER"],
        KZ: ["BIN", "OKPO"],
        LA: ["LEI"],
        LB: ["COMMERCIAL REGISTER NUMBER", "CHAMBER OF COMMERCE NUMBER"],
        LC: ["LEI"],
        LI: ["TRADE REGISTER NUMBER"],
        LK: ["TRADE REGISTER NUMBER"],
        LR: ["LEI", "SIREN NUMBER"],
        LS: ["TRADE REGISTER NUMBER"],
        LT: ["VAT NUMBER", "TRADE REGISTER NUMBER"],
        LU: ["EUROPEAN VAT NUMBER", "TRADE REGISTER NUMBER"],
        LV: ["VAT NUMBER", "TRADE REGISTER NUMBER"],
        LY: ["SIREN NUMBER"],
        MA: ["TRADE REGISTER NUMBER"],
        MC: ["RCI NUMBER", "SIREN NUMBER"],
        MD: ["IDNO"],
        ME: ["MATICNI BROJ"],
        MG: ["RCS NUMBER", "SIREN NUMBER"],
        MH: ["CIK", "LEI"],
        MK: ["TIN", "PIN"],
        ML: ["TRADE REGISTER NUMBER"],
        MM: ["TRADE REGISTER NUMBER"],
        MN: ["ISIN NUMBER"],
        MO: ["COMPANY NUMBER", "BELGIAN COMPANY NUMBER"],
        MR: ["LEI", "SIREN NUMBER"],
        MT: ["VAT NUMBER", "TRADE REGISTER NUMBER"],
        MU: ["TRADE REGISTER NUMBER"],
        MV: ["SIREN NUMBER"],
        MW: ["GIIN"],
        MX: ["RFC", "CIK"],
        MY: ["TRADE REGISTER NUMBER", "CIK"],
        MZ: ["LEI"],
        NA: ["TRADE REGISTER NUMBER"],
        NE: ["NIF", "RCCM NUMBER"],
        NG: ["RC NUMBER", "IMO NUMBER"],
        NI: ["LEI"],
        NL: ["EUROPEAN VAT NUMBER", "COC-NUMBER"],
        NO: ["ORGANIZATION NUMBER"],
        NP: ["ISIN NUMBER"],
        NR: ["SIREN NUMBER"],
        NZ: ["COMPANY NUMBER"],
        OM: ["COMMERCIAL REGISTER NUMBER", "CHAMBER OF COMMERCE NUMBER"],
        PA: ["TRADE REGISTER NUMBER"],
        PE: ["RUC"],
        PG: ["TRADE REGISTER NUMBER"],
        PH: ["SEC REGISTRATION NUMBER"],
        PK: ["TRADE REGISTER NUMBER"],
        PL: ["NCR NUMBER", "REGON NUMBER"],
        PR: ["TRADE REGISTER NUMBER", "EIN"],
        PS: ["COMMERCIAL REGISTER NUMBER", "CHAMBER OF COMMERCE NUMBER"],
        PT: ["EUROPEAN VAT NUMBER", "NIF"],
        PW: ["IMO NUMBER"],
        PY: ["RUC"],
        QA: ["COMMERCIAL REGISTER NUMBER", "CHAMBER OF COMMERCE NUMBER"],
        RO: ["EUROPEAN VAT NUMBER", "VAT NUMBER"],
        RS: ["VAT NUMBER", "TRADE REGISTER NUMBER"],
        RU: ["INN", "OGRN"],
        RW: ["ENTREPRISE CODE"],
        SA: ["COMMERCIAL REGISTER NUMBER", "CHAMBER OF COMMERCE NUMBER"],
        SB: ["SIREN NUMBER"],
        SC: ["ORGANIZATION NUMBER", "SIREN NUMBER"],
        SD: ["SIREN NUMBER"],
        SE: ["EUROPEAN VAT NUMBER", "TRADE REGISTER NUMBER"],
        SG: ["UEN"],
        SI: ["EUROPEAN VAT NUMBER", "VAT NUMBER"],
        SK: ["EUROPEAN VAT NUMBER", "VAT NUMBER"],
        SL: ["IMO NUMBER"],
        SM: ["LEI"],
        SN: ["CUCI NUMBER"],
        SO: ["IMO NUMBER"],
        SR: ["SIREN NUMBER"],
        SS: ["GIIN"],
        ST: ["IMO NUMBER"],
        SV: ["NIT"],
        SX: ["SIREN NUMBER"],
        SY: ["COMMERCIAL REGISTER NUMBER", "CHAMBER OF COMMERCE NUMBER"],
        SZ: ["ENTERPRISE NUMBER"],
        TD: ["SIREN NUMBER"],
        TG: ["TRADE REGISTER NUMBER"],
        TH: ["TRADE REGISTER NUMBER"],
        TJ: ["SIREN NUMBER"],
        TL: ["LEI"],
        TM: ["SIREN NUMBER"],
        TN: ["TRADE REGISTER NUMBER"],
        TO: ["IMO NUMBER"],
        TR: ["MERSIS NUMBER", "TRADE REGISTER NUMBER"],
        TT: ["LEI"],
        TV: ["IMO NUMBER"],
        TW: ["UNIFORM INVOICE NUMBER", "CIK"],
        TZ: ["TRADE REGISTER NUMBER"],
        UA: ["VAT NUMBER", "EDRPOU CODE"],
        UG: ["TRADE REGISTER NUMBER"],
        US: ["EIN", "CIK"],
        UY: ["RUT"],
        UZ: ["TRADE REGISTER NUMBER"],
        VA: ["SIREN NUMBER"],
        VC: ["LEI"],
        VE: ["RIF"],
        VG: ["LEI", "CIK"],
        VN: ["TRADE REGISTER NUMBER"],
        VU: ["LEI"],
        WS: ["LEI"],
        YE: ["COMMERCIAL REGISTER NUMBER", "CHAMBER OF COMMERCE NUMBER"],
        ZA: ["VAT NUMBER", "ENTERPRISE NUMBER"],
        ZM: ["LEI"],
        ZW: ["LEI"],
        GU: [],
        MP: [],
        FO: [],
        PF: [],
        GF: [],
        TF: [],
        FK: [],
        GL: [],
        GP: [],
        AN: [],
        HM: [],
        CC: [],
        CK: [],
        RE: [],
        MQ: [],
        YT: [],
        UM: [],
        AS: [],
        VI: [],
        MS: [],
        GS: [],
        YU: [],
        NU: [],
        NF: [],
        PN: [],
        SH: [],
        PM: [],
        SJ: [],
        TC: [],
        TK: [],
        WF: [],
        EH: [],
        NC: [],
        IO: [],
        CS: [],
        BV: [],
    },

}